### ISSUE TITLE
Change utility name

### ISSUE THREAD

**Issue by vricop** [vricop/PetricorCSS#2]
Change utility name to: 

```scss
.#{$prefix}grid-flow-col#{$state}    { grid-auto-flow: column;    } 
```

https://github.com/vricop/PetricorCSS/blob/11698aa243e1d1aa72facd29ed6695ff5ec8db9c/utility-generators/_grid-auto-flow.scss#L10
